apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-
namespace: url-shortener-prod

patches:
  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: postgres-patch.yaml
    target:
      kind: StatefulSet
      name: postgres

configMapGenerator:
  - name: url-shortener-config
    behavior: merge
    literals:
      - environment=production
      - api-url=https://api.url-shortener.com 