apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-backend
  labels:
    app: url-shortener
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
      component: backend
  template:
    metadata:
      labels:
        app: url-shortener
        component: backend
    spec:
      containers:
      - name: backend
        image: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-url-shortener-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DATABASE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30
      imagePullSecrets:
      - name: docker-registry 