apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
data:
  postgres-db: "url_shortener"
  environment: "development"
---
apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=  # base64 encoded "postgres"
  postgres-password: cG9zdGdyZXM=  # base64 encoded "postgres"
  database-url: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3JlcyQvcG9zdGdyZXM6NTQzMi91cmxfc2hvcnRlbmVy  # base64 encoded "postgres://postgres:postgres@postgres:5432/url_shortener" 