apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - postgres-deployment.yaml
  - services.yaml
  - config.yaml

commonLabels:
  app: url-shortener 