apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - postgres-deployment.yaml
  - frontend-service.yaml
  - backend-service.yaml
  - postgres-service.yaml
  - config.yaml

labels:
  - pairs:
      app: url-shortener 