apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - secrets.yaml

labels:
  - pairs:
      app: url-shortener

configMapGenerator:
  - name: url-shortener-config
    literals:
      - BACKEND_IMAGE=url-shortener-backend:latest
      - FRONTEND_IMAGE=url-shortener-frontend:latest

secretGenerator:
  - name: url-shortener-secrets
    literals:
      - database-url=postgresql://postgres:postgres@postgres:5432/url_shortener 