apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-
namespace: url-shortener-dev

patchesStrategicMerge:
  - frontend-patch.yaml
  - backend-patch.yaml
  - postgres-patch.yaml

configMapGenerator:
  - name: url-shortener-config
    behavior: merge
    literals:
      - environment=development
      - api-url=http://dev-url-shortener-backend:8000 