name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

env:
  REGISTRY: docker.io
  BACKEND_IMAGE_NAME: k8s-link-shortener-backend
  FRONTEND_IMAGE_NAME: k8s-link-shortener-frontend

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Download Docker images
      uses: actions/download-artifact@v3
      with:
        name: docker-images
        path: ./

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Load and push backend image
      run: |
        docker load < ./backend-image.tar
        docker tag url-shortener-backend:latest ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}

    - name: Load and push frontend image
      run: |
        docker load < ./frontend-image.tar
        docker tag url-shortener-frontend:latest ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        echo "KUBECONFIG=kubeconfig" >> $GITHUB_ENV

    - name: Update image tags
      run: |
        cd k8s/overlays/prod
        kustomize edit set image url-shortener-backend=${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}
        kustomize edit set image url-shortener-frontend=${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -k k8s/overlays/prod
        kubectl rollout status deployment/prod-url-shortener-backend -n url-shortener-prod
        kubectl rollout status deployment/prod-url-shortener-frontend -n url-shortener-prod 