name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend dependencies
      working-directory: ./app/backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test backend
      working-directory: ./app/backend
      run: |
        python -m pytest

    - name: Install frontend dependencies
      working-directory: ./app/frontend
      run: npm install

    - name: Test frontend
      working-directory: ./app/frontend
      run: npm test

    - name: Build frontend
      working-directory: ./app/frontend
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./app/backend
        push: false
        tags: url-shortener-backend:latest

    - name: Build frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./app/frontend
        push: false
        tags: url-shortener-frontend:latest 